### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by EallanW** [AndreaLombardo/BootSideMenu#4]
I use BootSideMenu in my project, and the error is as follow, how could I solve it?

angular.js:12221 
TypeError: $(...).BootSideMenu is not a function
    at HTMLDocument.eval (eval at <anonymous> (http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:2620), <anonymous>:3:18)
    at j (http://localhost:8081/SurveyTemplate/templates/4/assets/js/jquery.min.js:2:27136)
    at Object.k.add [as done](http://localhost:8081/SurveyTemplate/templates/4/assets/js/jquery.min.js:2:27445)
    at n.fn.ready (http://localhost:8081/SurveyTemplate/templates/4/assets/js/jquery.min.js:2:29551)
    at eval (eval at <anonymous> (http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:2620), <anonymous>:2:15)
    at eval (native)
    at http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:2620
    at Function.m.extend.globalEval (http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2:2631)
    at m.fn.extend.domManip (http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:22994)
    at m.fn.extend.append (http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:20507) <div ng-include="'/SurveyTemplate/CommonCode/Utilities.html'" class="ng-scope">

**Comment by AndreaLombardo** [comment]
Hi, I'm not in place for now and the project was only a beta... Anyway Is better for me if you attach the code where BootSideMenu is used. 
Thanks

**Comment by AndreaLombardo** [comment]
This project is incomplete and no longer maintained, I'm working on a new version but I'm very busy on my job. Hoping the new version can include your request.
Thanks for your interesting
